version: '3.5'

services:
  vessels-view:
    ports:
      - target: ${VIEW_PORT}
        published: ${VIEW_PORT}
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "${VIEW_PORT}"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: PathPrefix:/api/${UNIT_NAME}/view
        traefik.backend: ${UNIT_NAME}-view
      restart_policy:
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '1'
          memory: 768M
        reservations:
          memory: 615M
