version: '3.5'

services:
  vessels-view:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - VIEW_PORT
      - SPRING_PROFILES_ACTIVE
      - OAUTH_CLIENT_ID
      - OAUTH_CLIENT_SECRET
      - ELASTIC_XPACKSECURITYUSER
      - MICROSERVICE_NAME=${UNIT_NAME}-view
      - SPRING_KAFKA_CLIENT-ID={{.Service.Name}}-{{.Task.Slot}}
      - JAVA_OPTS=-XX:MaxRAMFraction=2
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "${VIEW_PORT}"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: PathPrefix:/api/${UNIT_NAME}/view
        traefik.backend: ${UNIT_NAME}-view
      restart_policy:
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '1'
          memory: 768M
        reservations:
          memory: 615M
    networks:
      - elastic-net
      - metrics-net
      - kafka-net
      - redmic-net
      - traefik-net
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${VIEW_PORT}/api/${UNIT_NAME}/view/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m

networks:
  elastic-net:
    external: true

  kafka-net:
    external: true

  redmic-net:
    external: true

  traefik-net:
    external: true
