version: '3.5'

services:
  vessels-commands:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - COMMANDS_PORT
      - SPRING_PROFILES_ACTIVE
      - OAUTH_CLIENT_ID
      - OAUTH_CLIENT_SECRET
      - MICROSERVICE_NAME=${UNIT_NAME}-commands
      - SPRING_KAFKA_CLIENT-ID={{.Service.Name}}-{{.Task.Slot}}
      - JAVA_OPTS=-XX:MaxRAMFraction=2
    networks:
      - kafka-net
      - redmic-net
      - traefik-net
    volumes:
      - commands-vol:/tmp/kafka
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${COMMANDS_PORT}/api/${UNIT_NAME}/commands/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m

networks:
  kafka-net:
    external: true

  redmic-net:
    external: true

  traefik-net:
    external: true
