version: '3.5'

services:
  vessels-commands:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - COMMANDS_PORT
      - SPRING_PROFILES_ACTIVE
      - OAUTH_CLIENT_ID
      - OAUTH_CLIENT_SECRET
      - MICROSERVICE_NAME=${UNIT_NAME}-commands
      - JAVA_OPTS=-XX:MaxRAMFraction=2
    networks:
      - kafka-net
      - redmic-net
      - traefik-net
    volumes:
      - commands-vol:/tmp/kafka
    healthcheck:
      test: wget --spider -q http://localhost:${COMMANDS_PORT}/api/${UNIT_NAME}/commands/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.frontend.rule: Host:${PUBLIC_HOSTNAME};PathPrefix:/api/${UNIT_NAME}/commands
        traefik.backend: ${UNIT_NAME}-commands
        traefik.port: "${COMMANDS_PORT}"
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          memory: 820M

networks:
  kafka-net:
    external: true

  redmic-net:
    external: true

  traefik-net:
    external: true
