version: '3.5'

services:
  vessels-commands:
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "${COMMANDS_PORT}"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: PathPrefix:/api/${UNIT_NAME}/commands
        traefik.backend: ${UNIT_NAME}-commands
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        delay: 1m
        window: 3m
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          memory: 820M

volumes:
  commands-vol:
    name: "${UNIT_NAME}-commands-{{.Task.Slot}}-vol"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 1
      ebstype: gp2
