version: '3.5'

services:
  vessels-commands:
    deploy:
      placement:
        constraints:
          - node.role == worker

volumes:
  commands-vol:
    name: "${UNIT_NAME}-commands-{{.Task.Slot}}-vol"
    driver: "cloudstor:aws"
    driver_opts:
      backing: relocatable
      size: 1
      ebstype: gp2
